### 주문 생성
//@no-log
POST {{host_url}}/v1/users/orders
Content-Type: application/json

{
  "documents": [
    {
      "name": "홍보 전단지",
      "page_count": 5,
      "recovery_option": "SPRING",
      "is_ocr_enabled": false
    },
    {
      "name": "카탈로그",
      "page_count": 10,
      "recovery_option": "SPRING",
      "is_ocr_enabled": false
    }
  ],
  "delivery_info": {
    "receiver_name": "김철수",
    "phone_number": "01012345678",
    "email": "kimchulsoo@example.com",
    "request": "배송 전 연락 부탁드립니다.",
    "address": {
      "zipcode": "12345",
      "address1": "서울특별시 강남구 테헤란로 123",
      "address2": "강남빌딩 5층"
    }
  },
  "is_one_day_scan": false
}

### 주문 조회
//@no-log
GET {{host_url}}/v1/users/orders/overviews?page=1&size=10&sort=createdAt
Authorization: Bearer {{access_token}}

### 결제 요청
//@no-log
PATCH {{host_url}}/v1/admins/orders/734276020051665347/payment-requests

### PDF 전송
//@no-log
POST {{host_url}}/v1/admins/orders/19/send-pdfs
Authorization: Bearer {{access_token}}

### 관리자 주문 조회
//@no-log
GET {{host_url}}/v1/admins/orders/overviews?page=1&size=10&start-date=2025-02-12&end-date=2025-03-12&sort=order-date&direction=DESC
Authorization: Bearer {{access_token}}

### 관리자 결제 조회
//@no-log
GET {{host_url}}/v1/admins/orders/688623424943448498/payments/overviews
Authorization: Bearer {{access_token}}

### 관리자 주문 상세 조회
//@no-log
GET {{host_url}}/v1/admins/orders/732163380529619446/details

### 관리자 pdf 업로드
//@no-log
POST {{host_url}}/v1/admins/documents/732163380542202321/pdfs
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< /Users/kyeom/Desktop/Project/PDF-Watermark/src/main/resources/test.pdf

### 관리자 PDF 워터마크 검수
//@no-log
POST {{host_url}}/v1/admins/pdfs/validation
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="new_test.pdf"
Content-Type: application/pdf

< /Users/kyeom/Desktop/tset_732163380542202321.pdf

### 관리자 운송장 등록
//@no-log
PATCH {{host_url}}/v1/admins/deliveries/734571270750274302/tracking-number
Content-Type: application/json

{
  "tracking_number": "1234567890"
}