package com.tookscan.tookscan.order.presentation.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tookscan.tookscan.core.dto.SelfValidating;
import com.tookscan.tookscan.order.domain.CouponTemplate;
import com.tookscan.tookscan.order.domain.type.ECouponFormat;
import com.tookscan.tookscan.order.domain.type.ECouponType;
import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

@Getter
public class ReadAdminCouponTemplateDetailResponseDto extends SelfValidating<ReadAdminCouponTemplateDetailResponseDto> {

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    @JsonProperty("format")
    private final ECouponFormat format;

    @JsonProperty("auto_generated_count")
    private final Integer autoGeneratedCount;

    @JsonProperty("auto_generated_tag")
    private final String autoGeneratedTag;

    @JsonProperty("defined_code")
    private final String definedCode;

    @JsonProperty("defined_max_used_count")
    private final Integer definedMaxUsedCount;

    @JsonProperty("type")
    private final ECouponType type;

    @JsonProperty("discount_price")
    private final Integer discountPrice;

    @JsonProperty("discount_percent")
    private final Integer discountPercent;

    @JsonProperty("max_discount_price")
    private final Integer maxDiscountPrice;

    @JsonProperty("min_order_price")
    private final Integer minOrderPrice;

    @JsonProperty("start_date_time")
    private final LocalDateTime startDateTime;

    @JsonProperty("end_date_time")
    private final LocalDateTime endDateTime;

    @JsonProperty("max_used_per_user_count")
    private final Integer maxUsedPerUserCount;

    @Builder
    public ReadAdminCouponTemplateDetailResponseDto(
            String id,
            String name,
            ECouponFormat format,
            Integer autoGeneratedCount,
            String autoGeneratedTag,
            String definedCode,
            Integer definedMaxUsedCount,
            ECouponType type,
            Integer discountPrice,
            Integer discountPercent,
            Integer maxDiscountPrice,
            Integer minOrderPrice,
            LocalDateTime startDateTime,
            LocalDateTime endDateTime,
            Integer maxUsedPerUserCount
    ) {
        this.id = id;
        this.name = name;
        this.format = format;
        this.autoGeneratedCount = autoGeneratedCount;
        this.autoGeneratedTag = autoGeneratedTag;
        this.definedCode = definedCode;
        this.definedMaxUsedCount = definedMaxUsedCount;
        this.type = type;
        this.discountPrice = discountPrice;
        this.discountPercent = discountPercent;
        this.maxDiscountPrice = maxDiscountPrice;
        this.minOrderPrice = minOrderPrice;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
        this.maxUsedPerUserCount = maxUsedPerUserCount;

        this.validateSelf();
    }

    public static ReadAdminCouponTemplateDetailResponseDto of(CouponTemplate couponTemplate,
                                                              Integer autoGeneratedCount,
                                                              String autoGeneratedTag,
                                                              String definedCode,
                                                              Integer definedMaxUsedCount) {
        return ReadAdminCouponTemplateDetailResponseDto.builder()
                .id(couponTemplate.getId().toString())
                .name(couponTemplate.getName())
                .format(couponTemplate.getFormat())
                .autoGeneratedCount(autoGeneratedCount)
                .autoGeneratedTag(autoGeneratedTag)
                .definedCode(definedCode)
                .definedMaxUsedCount(definedMaxUsedCount)
                .type(couponTemplate.getType())
                .discountPrice(couponTemplate.getDiscountPrice())
                .discountPercent(couponTemplate.getDiscountPercent())
                .maxDiscountPrice(couponTemplate.getMaxDiscountPrice())
                .minOrderPrice(couponTemplate.getMinOrderPrice())
                .startDateTime(couponTemplate.getStartDateTime())
                .endDateTime(couponTemplate.getEndDateTime())
                .maxUsedPerUserCount(couponTemplate.getMaxUsedPerUserCount())
                .build();
    }


}
