spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    com:
      ivory.ivory: debug

jwt:
  secret: ${JWT_SECRET}