spring:
  application:
    name: "TOOK-SCAN Main Server API"
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---