package com.tookscan.tookscan.order.application.service;

import com.tookscan.tookscan.core.annotation.BusinessLog;
import com.tookscan.tookscan.core.exception.error.ErrorCode;
import com.tookscan.tookscan.core.exception.type.CommonException;
import com.tookscan.tookscan.core.util.LogContext;
import com.tookscan.tookscan.order.application.usecase.CreateAdminOrderCouponUseCase;
import com.tookscan.tookscan.order.domain.CouponTemplate;
import com.tookscan.tookscan.order.domain.IssuedCoupon;
import com.tookscan.tookscan.order.presentation.dto.request.CreateAdminOrderCouponRequestDto;
import com.tookscan.tookscan.order.repository.CouponTemplateRepository;
import com.tookscan.tookscan.order.repository.IssuedCouponRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class CreateAdminOrderCouponService implements CreateAdminOrderCouponUseCase {

    private final CouponTemplateRepository couponTemplateRepository;
    private final IssuedCouponRepository issuedCouponRepository;

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    @Override
    @Transactional
    @BusinessLog(
        domain = "Order",
        action = "create coupon",
        userType = "Admin"
    )
    public void execute(CreateAdminOrderCouponRequestDto requestDto) {

        CouponTemplate couponTemplate = CouponTemplate.builder()
                .name(requestDto.name())
                .format(requestDto.format())
                .tag(requestDto.autoGeneratedTag())
                .type(requestDto.type())
                .discountPrice(requestDto.discountPrice())
                .discountPercent(requestDto.discountPercent())
                .maxDiscountPrice(requestDto.maxDiscountPrice())
                .minOrderPrice(requestDto.minOrderPrice())
                .maxUsedPerUserCount(requestDto.maxUsedPerUserCount())
                .startDateTime(requestDto.startDateTime())
                .endDateTime(requestDto.endDateTime())
                .build();

        // 쿠폰 템플릿 저장
        couponTemplateRepository.save(couponTemplate);

        // 발행 쿠폰 생성
        switch (couponTemplate.getFormat()) {
            case AUTO_GENERATED -> {
                List<IssuedCoupon> issuedCoupons = new ArrayList<>();

                for (int i = 0; i < requestDto.autoGeneratedCount(); i++) {
                    String couponCode = createUniqueCouponCode(requestDto.autoGeneratedTag());
                    IssuedCoupon issuedCoupon = IssuedCoupon.builder()
                            .couponTemplate(couponTemplate)
                            .code(couponCode)
                            .usedCount(0)
                            .maxUsedCount(1)
                            .build();
                    issuedCoupons.add(issuedCoupon);
                }
                issuedCouponRepository.saveAll(issuedCoupons);
            }

            case DEFINED -> {
                if (issuedCouponRepository.existsByCouponCode(requestDto.definedCode())) {
                    throw new CommonException(ErrorCode.DUPLICATE_COUPON_CODE);
                }

                IssuedCoupon issuedCoupon = IssuedCoupon.builder()
                        .couponTemplate(couponTemplate)
                        .code(requestDto.definedCode())
                        .usedCount(0)
                        .maxUsedCount(requestDto.definedMaxUsedCount())
                        .build();
                issuedCouponRepository.save(issuedCoupon);
            }
        }

        LogContext.put("coupon_name", requestDto.name());
    }

    private String createUniqueCouponCode(String tag) {
        String couponCode;
        int attempts = 0;
        do {
            couponCode = this.generateCouponCode(tag);
            attempts++;
            int MAX_ATTEMPTS = 10;
            if (attempts >= MAX_ATTEMPTS) {
                throw new CommonException(ErrorCode.INTERNAL_SERVER_ERROR, "중복되지 않는 쿠폰 코드를 생성하지 못했습니다.");
            }
        } while (issuedCouponRepository.existsByCouponCode(couponCode));
        return couponCode;
    }

    private String generateCouponCode(String tag) {
        int randomPartLength = 10 - tag.length();
        return tag + generateRandomAlphanumeric(randomPartLength);
    }

    private String generateRandomAlphanumeric(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            int index = RANDOM.nextInt(CHARACTERS.length());
            sb.append(CHARACTERS.charAt(index));
        }
        return sb.toString();
    }
}
