package com.tookscan.tookscan.order.application.service;

import com.tookscan.tookscan.core.exception.error.ErrorCode;
import com.tookscan.tookscan.core.exception.type.CommonException;
import com.tookscan.tookscan.order.application.usecase.ReadAdminCouponTemplateDetailUseCase;
import com.tookscan.tookscan.order.domain.CouponTemplate;
import com.tookscan.tookscan.order.domain.IssuedCoupon;
import com.tookscan.tookscan.order.presentation.dto.response.ReadAdminCouponTemplateDetailResponseDto;
import com.tookscan.tookscan.order.repository.CouponTemplateRepository;
import com.tookscan.tookscan.order.repository.IssuedCouponRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class ReadAdminCouponTemplateDetailService implements ReadAdminCouponTemplateDetailUseCase {

    private final CouponTemplateRepository couponTemplateRepository;
    private final IssuedCouponRepository issuedCouponRepository;

    @Override
    public ReadAdminCouponTemplateDetailResponseDto execute(Long couponId) {
        // 쿠폰 템플릿 조회
        CouponTemplate couponTemplate = couponTemplateRepository.findByIdOrElseThrow(couponId);

        // 쿠폰 템플릿의 쿠폰 포멧에 따른 인자값 결정
        Integer autoGeneratedCount = null;
        String autoGeneratedTag = null;
        String definedCode = null;
        Integer definedMaxUsedCount = null;

        IssuedCoupon issuedCouponExample = issuedCouponRepository.findByCouponTemplateId(couponTemplate.getId())
                .stream()
                .findFirst()
                .orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_ISSUED_COUPON, "발행된 쿠폰이 없습니다."));

        switch (couponTemplate.getFormat()) {
            case DEFINED -> {
                definedCode = issuedCouponExample.getCode();
                definedMaxUsedCount = issuedCouponExample.getMaxUsedCount();
            }
            case AUTO_GENERATED -> {
                autoGeneratedCount = issuedCouponExample.getMaxUsedCount();
                autoGeneratedTag = couponTemplate.getTag();
            }
            default -> throw new CommonException(ErrorCode.INVALID_ENUM_TYPE, "유효하지 않은 쿠폰 포맷: " + couponTemplate.getFormat());
        }

        return ReadAdminCouponTemplateDetailResponseDto.of(couponTemplate,
                autoGeneratedCount, autoGeneratedTag, definedCode, definedMaxUsedCount);
    }
}
