### 테스트 메일 발송
//@no-log
POST {{host_url}}/v1/test-email
Content-Type: application/json

{
  "email": "jangelliot0404@dgu.ac.kr"
}

### 테스트 메일 발송 여부 검증
// @no-log
GET {{host_url}}/v1/validation/test-email?email=jangelliot0404@dgu.ac.kr
