package com.tookscan.tookscan.order.presentation.dto.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tookscan.tookscan.order.domain.type.ECouponFormat;
import com.tookscan.tookscan.order.domain.type.ECouponType;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

public record CreateAdminOrderCouponRequestDto(
        @JsonProperty("name")
        @NotBlank(message = "쿠폰 이름을 입력해주세요.")
        String name,

        @JsonProperty("format")
        @NotNull(message = "쿠폰 형식을 입력해주세요.")
        ECouponFormat format,

        @JsonProperty("auto_generated_count")
        Integer autoGeneratedCount,

        @JsonProperty("auto_generated_tag")
        @Pattern(
                regexp = "^[A-Z]{2,5}$",
                message = "태그 형식이 올바르지 않습니다."
        )
        String autoGeneratedTag,

        @JsonProperty("defined_code")
        @Pattern(
                regexp = "^[A-Z]{2,5}\\d{5,8}$",
                message = "쿠폰 코드 형식이 올바르지 않습니다."
        )
        String definedCode,

        @JsonProperty("defined_max_used_count")
        Integer definedMaxUsedCount,

        @JsonProperty("type")
        @NotNull(message = "쿠폰 타입을 입력해주세요.")
        ECouponType type,

        @JsonProperty("discount_price")
        @Min(0)
        Integer discountPrice,

        @JsonProperty("discount_percent")
        @Min(1)
        @Max(100)
        Integer discountPercent,

        @JsonProperty("max_discount_price")
        Integer maxDiscountPrice,

        @JsonProperty("min_order_price")
        Integer minOrderPrice,

        @JsonProperty("start_date_time")
        LocalDateTime startDateTime,

        @JsonProperty("end_date_time")
        LocalDateTime endDateTime,

        @JsonProperty("max_used_per_user_count")
        Integer maxUsedPerUserCount
) {
}
